Part 1: Introduction

What is NumPy?
1. Numerical Python library for arrays & matrices
2. Much faster than Python lists (because it uses C under the hood)
3. Why do we need NumPy? (AI/ML, data science, image processing, etc.)

In [5]:
!pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 26.5 MB/s  0:00:00m0:00:0100:01


In [6]:
import numpy as np

In [7]:
lst = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])

print(type(lst))   # list
print(type(arr))   # numpy.ndarray

<class 'list'>
<class 'numpy.ndarray'>


Part 2: Creating Arrays

In [17]:
a = np.array([1, 2, 3])           # 1D
b = np.array([[1, 2], [3, 4]])    # 2D
c = np.zeros((3, 3))              # 3x3 of zeros
d = np.ones((2, 2))               # 2x2 of ones
e = np.arange(0, 10, 2)           # [0, 2, 4, 6, 8]
f = np.linspace(0, 1, 5)          # [0. , 0.25, 0.5 , 0.75, 1. ] #evenly spaced values
g = np.eye(3, 3)                     # 3x3 Identity matrix 

print("a =", a)
print("b =", b)
print("c =", c)
print("d =", d)
print("e =", e)
print("f =", f)
print("g =", g)

a = [1 2 3]
b = [[1 2]
 [3 4]]
c = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
d = [[1. 1.]
 [1. 1.]]
e = [0 2 4 6 8]
f = [0.   0.25 0.5  0.75 1.  ]
g = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
A = np.full((5, 5), 7)      #5x5 matrix of all 7s
print(A)

B = np.linspace(10, 51, 20)  #A vector of 20 values from 10 to 50 equally spaced
print(B)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[10.         12.15789474 14.31578947 16.47368421 18.63157895 20.78947368
 22.94736842 25.10526316 27.26315789 29.42105263 31.57894737 33.73684211
 35.89473684 38.05263158 40.21052632 42.36842105 44.52631579 46.68421053
 48.84210526 51.        ]


Part 3: Array Attributes

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)   # (2, 3)
print(arr.size)    # 6  #total number of elements


(2, 3)
6


Part 4: Indexing & Slicing

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[0])      # 10
print(arr[-1])     # 50
print(arr[1:4])    # [20 30 40]

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0, 2])       # 3
print(matrix[:,1])        # [2 5 8] #all rows, column 1
print(matrix[1:3, 0:2])                # [[4 5]
            #rows #columns          #  [7 8]]   # rows 1-2, columns 0-1

#extract 2nd column from 3x3 matrix

10
50
[20 30 40]
3
[2 5 8]
[[4 5]
 [7 8]]
[2 5 8]


Part 5: Mathematical Operations

In [23]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)   # [5 7 9]
print(x * y)   # [ 4 10 18]
print(x ** 2)  # [1 4 9]

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A @ B)   # matrix multiplication
print(A.dot(B)) # matrix multiplication
print(A.T)     # transpose of A 

[5 7 9]
[ 4 10 18]
[1 4 9]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


Part 6: Aggregate Functions

In [ ]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2.sum())    # 15
print(arr2.mean())   # 3.0
print(arr2.max())    # 5
print(arr2.min())    # 1
print(arr2.argmax()) # 4  #index of max element
print(arr2.argmin()) # 0  #index of min element

15
3.0
5
1
4
0


Part 7: Reshaping & Stacking

In [ ]:
arr = np.arange(12)   # [0 1 2 ... 11]
print(arr.reshape(3,4))   # 3x4
print(arr.reshape(2,6))   # 2x6  #total elements must match

a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))     #Stacks arrays on top of each other (row-wise).
print(np.hstack((a,b)))     #Stacks arrays side by side (column-wise).


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Part 8: Random Numbers

In [ ]:
a1 = np.random.rand(3,3)   # uniform distribution -> every number between 0 and 1 is equally likely.
print(a1)
a2 = np.random.randn(3,3)  # normal distribution -> values can be negative or positive, clustering around 0.
                           #Values are sampled from a normal distribution (bell curve).

Mean = 0, Standard Deviation = 1 by default.
print(a2)
a3 = np.random.randint(1,10,(2,3))  # random ints 1-9 #Generates a 2×3 matrix of random integers.
                                    #Integers are between 1 (inclusive) and 10 (exclusive) → so values are 1 to 9.
print(a3)

[[0.50292612 0.9600604  0.45524596]
 [0.99103166 0.65870565 0.91576905]
 [0.66733241 0.35822701 0.10749479]]
[[-0.1614453   0.98639478 -1.5365036 ]
 [ 0.12641909 -1.83497485 -0.22141495]
 [ 0.66771605 -0.08384726 -0.99704358]]
[[1 8 2]
 [7 9 6]]
